apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  name: prometheus-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: prometheus
spec:
  groups:
  - name: otusk8s3
    rules:
    - alert: Otusk8s3LatencyHigh
      expr: histogram_quantile(0.99, sum(rate(otusk8s3_request_latency_seconds_bucket[2m])) by (le)) > 3
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Otusk8s3 latency high (instance {{ $labels.instance }})
        description: "Otusk8s3 p99 latency is higher than 3 seconds\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

    - alert: Otusk8s3HighHttp5xxErrorRate
      expr: sum(rate(otusk8s3_request_count{http_status=~"^5.."}[1m])) / sum(rate(otusk8s3_request_count[1m])) * 100 > 5
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: Otusk8s3 high HTTP 5xx error rate (instance {{ $labels.instance }})
        description: "Too many HTTP requests with status 5xx (> 5%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
