{
 "title": "OTUS Homework",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "PostgreSQL Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{datname=\"otusk8s3\"}"
    }
   ]
  },
  {
   "title": "PostgreSQL QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(pg_stat_database_xact_commit{datname=\"otusk8s3\"}[5m])) + sum(irate(pg_stat_database_xact_rollback{datname=\"otusk8s3\"}[5m]))"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by(le, method, exported_endpoint) (\n    rate(otusk8s3_request_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.5,\n  sum by(le, method, exported_endpoint) (\n    rate(otusk8s3_request_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(le, method, exported_endpoint) (\n    rate(otusk8s3_request_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency p100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  1,\n  sum by(le, method, exported_endpoint) (\n    rate(otusk8s3_request_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(otusk8s3_request_count[1m])) by (method, exported_endpoint)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(otusk8s3_request_count{http_status=\"500\"}[1m])) by (method, exported_endpoint)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "Latency p50 (nginx-ingress-controller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by(le, method, path) (\n    rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{path}}"
    }
   ]
  },
  {
   "title": "Latency p95 (nginx-ingress-controller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by(le, method, path) (\n    rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{path}}"
    }
   ]
  },
  {
   "title": "Latency p99 (nginx-ingress-controller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by(le, method, path) (\n    rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{path}}"
    }
   ]
  },
  {
   "title": "Latency p100 (nginx-ingress-controller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  1,\n  sum by(le, method, path) (\n    rate(nginx_ingress_controller_response_duration_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "{{ method }} {{path}}"
    }
   ]
  },
  {
   "title": "RPS (nginx-ingress-controller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Error Rate (nginx-ingress-controller)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=\"500\"}[1m])) by (method, exported_endpoint)",
     "legendFormat": "{{method}} {{exported_endpoint}}"
    }
   ]
  },
  {
   "title": "otusk8s3 CPU Usage (Kubernetes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"otusk8s3\"}[5m])",
     "legendFormat": "otusk8s3"
    }
   ]
  },
  {
   "title": "otusk8s3 RAM Usage (Kubernetes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{container=\"otusk8s3\"}[5m])",
     "legendFormat": "otusk8s3"
    }
   ]
  }
 ]
}